#!/usr/bin/env python3
"""Generate i18n/ru.po and i18n/en.po from i18n/strings.tsv (key<TAB>ru<TAB>en).

Usage: python3 tools/gen_i18n.py [--check]
--check exits with 1 if the .po files are out of date (tools/verify.sh). Interface text lives only in
strings.tsv: add a row, rerun, and use the key with tr() in nodes or Loc.t() in static code.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "i18n" / "strings.tsv"


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def load():
    rows = []
    seen = set()
    for n, line in enumerate(SRC.read_text(encoding="utf-8").splitlines(), 1):
        if not line.strip() or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) != 3:
            sys.exit(f"strings.tsv:{n}: expected key<TAB>ru<TAB>en, got {len(parts)} columns")
        key, ru, en = (p.strip() for p in parts)
        if key in seen:
            sys.exit(f"strings.tsv:{n}: duplicate key {key}")
        if not ru or not en:
            sys.exit(f"strings.tsv:{n}: {key} needs both ru and en")
        seen.add(key)
        rows.append((key, ru.replace("\\n", "\n"), en.replace("\\n", "\n")))
    return rows


def po(rows, lang, col):
    out = ['# Generated by tools/gen_i18n.py from i18n/strings.tsv. Do not edit by hand.', 'msgid ""', 'msgstr ""',
           '"Content-Type: text/plain; charset=UTF-8\\n"', f'"Language: {lang}\\n"', ""]
    for row in rows:
        out.append(f'msgid "{esc(row[0])}"')
        out.append('msgstr "' + esc(row[col]).replace("\n", "\\n") + '"')
        out.append("")
    return "\n".join(out)


def main():
    rows = load()
    files = {ROOT / "i18n" / "ru.po": po(rows, "ru", 1), ROOT / "i18n" / "en.po": po(rows, "en", 2)}
    if "--check" in sys.argv:
        stale = [p.name for p, text in files.items() if not p.exists() or p.read_text(encoding="utf-8") != text]
        if stale:
            sys.exit("i18n out of date: " + ", ".join(stale) + " (run python3 tools/gen_i18n.py)")
        print(f"i18n OK: {len(rows)} strings")
        return
    for p, text in files.items():
        p.write_text(text, encoding="utf-8")
    print(f"wrote {len(files)} files, {len(rows)} strings")


if __name__ == "__main__":
    main()
